name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.432'
          distribution: 'temurin'
          check-latest: false


      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
          enableCrossOsArchive: false
        continue-on-error: true

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          echo "Build completed. Listing files in the target directory:"
          ls -l target/
          
          echo "Exact path of urls-0.0.1.jar:"
          realpath target/urls-0.0.1.jar

      - name: Transfer JAR to VPS
        run: |
          scp target/urls-0.0.1.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/urlApp


      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            
            # Define variables
            JAR_NAME="urls-0.0.1.jar"
            APP_DIR="/root/${{ secrets.VPS_USER }}/urlApp/"
            REMOTE_JAR_PATH="$APP_DIR$JAR_NAME"
            LOG_FILE="$APP_DIR/logfile.log"
            SPRING_PROFILE="prod"
            echo "/home/runner/work/urls/urls/target/urls-0.0.1.jar"
            
            
            # Stop existing Java process
            echo 'Stopping existing Java process'
            pkill -f "java -Dspring.profiles.active=$SPRING_PROFILE -jar $JAR_NAME" || true
            sleep 7
  
            
            # Start new Java process
            echo "Starting new Java process"
            nohup java -jar $REMOTE_JAR_PATH --spring.profiles.active=$SPRING_PROFILE > $LOG_FILE 2>&1 &

