name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.432'
          distribution: 'temurin'
          check-latest: false

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            pkill -f 'java -jar urls-0.0.1.jar' || true
            scp target/urls-0.0.1.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/${{ secrets.VPS_USER }}/urlApp/
            nohup java -jar /root/${{ secrets.VPS_USER }}/urlApp/urls-0.0.1.jar --spring.profiles.active=prod > /root/${{ secrets.VPS_USER }}/urlApp/log.out 2>&1 &


