name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.432'
          distribution: 'temurin'
          check-latest: false


      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            
            #Checking the jar directory
            echo "Listing files in target directory"
            ls target
            echo "Listing files in github workspace target directory"
            ls ${{ github.workspace }}/target
            
            
            
            # Define variables
            JAR_NAME="urls-0.0.1.jar"
            APP_DIR="/root/${{ secrets.VPS_USER }}/urlApp/"
            REMOTE_JAR_PATH="$APP_DIR$JAR_NAME"
            LOG_FILE="$APP_DIR/logfile.log"
            SPRING_PROFILE="prod"
            
            # Stop existing Java process
            echo 'Stopping existing Java process'
            pkill -f "java -Dspring.profiles.active=$SPRING_PROFILE -jar $JAR_NAME" || true
            sleep 7
            
            # Copy new JAR file to VPS
            echo "Copying new JAR to VPS"
            scp ${{ github.workspace }}/target/$JAR_NAME ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$REMOTE_JAR_PATH
            if [ $? -ne 0 ]; then
            echo "SCP failed"
            exit 1
            fi
            
            # Start new Java process
            echo "Starting new Java process"
            nohup java -jar $REMOTE_JAR_PATH --spring.profiles.active=$SPRING_PROFILE > $LOG_FILE 2>&1 &

