name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.432'
          distribution: 'temurin'
          check-latest: false


      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
          enableCrossOsArchive: false
        continue-on-error: true

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          echo "Build completed. Listing files in the target directory:"
          ls -l target/
          
          echo "Exact path of urls-0.0.1.jar:"
          realpath target/urls-0.0.1.jar

      - name: Transfer JAR to VPS
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no target/urls-0.0.1.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/urlApp/
        shell: bash



      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/urlApp/
            bash deploy_app.sh

            # Check deployment status
            if [ -f "github_action_status.env" ]; then
              source github_action_status.env
              if [ "$DEPLOYMENT_STATUS" != "success" ]; then
                echo "Deployment failed on VPS."
                exit 1
              fi
            else
              echo "Deployment status file not found!"
              exit 1
            fi
          
